name: Print env
on:
  push:
    branches:
      - main
env: 
  JDK_VERSION: "openjdk11-jdk"
jobs:  
  install-java:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: install java
        run: |
          apk add --no-cache $JDK_VERSION
          java --version
      
  print-env:
    runs-on: ubuntu-latest
    steps:
      - name: env print
        run: echo $JDK_VERSION
